language: node_js
node_js:
- node
sudo: required
services:
- docker
cache:
  directories:
  - node_modules
before_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- ./scripts/prepare-repo

script:
- yarn tslint
- yarn test
- yarn build
- yarn docker
- yarn docker:push
env:
  global:
  - secure: JZU/wMSEQfUObS0NXk2qU03Z+ggtWPPH3IwRJxocEX1Fp0qcgJzEb03IVzf36ep/da81MZAe/pUUUayJS3XbxPzi4cLSdGqi4FCQLL+deYnbJwkme+OPjTnawcdaBCVJ0+rIkYpoDc4blm4f2/G6CT0dIYXpoQEGBUAY9cD4Xi81F9WdNlMbUnliQDLJ8nFUvX4HrgdmKOIYDTqmZn7xD4wxB77gagxJYEuHO2LQbiEvvHa0FmSr+Y/h7R/kJpy4ZGXtQYQIwk6+FWeOTUcqvLJRUHT1MuIzhMepzIcvQwskfAITfG+2guMj10rr+FpRAsHbLP8+xKJHT1t8d6rJj0QF7JRP2ayXzx274fxcg3OYQco0kWLG0U6u+LPheo7N0VOPT4Qy/bvGk6M2KUpQvaO3Q5HULtyVbvpCfQG1iGmOofjYBDztgYdDXQnFx+Sd/y6BsiURRgVojxhwn3aGSO5N+boP6FZ/vVtAHSGfEt2c+ncvTnTYHYP5Qgzp9igv3PHjIno68BBycgcivSBI2KjkXwDDxFNd0TKacn+ASOFUinnCVZwnJ9ONbkRAeF6v2akNZHy0q2T8jjWA1Fdy5wmHI2v/dAXMqNFtGIivIW/T8WcyamjSmPUIxAHRG/lJqo9h87cd4kcrTjdKen3rNqFKTEuvLkwZ1e3T+RsQ/Ow=
  - secure: Vu8WgFdpwvmjocGqpHS+aTM/Q9khXpV4toXAupyOVXx4gn1Tl2AL9pE0bivqy8kvAmNZcUbp6m3REzEMoncTbCRkC1YXEqRWs3ayph1c4rK9Ufa993mXWi1p4MrGmQrmW+jSI+GlhxltoZLqJpTNvQiLtCqyliF6YgqtBGcPgeD9lyQ2x03CoEbB88GhtIWxV0crdgwPEU9DIZx5D2/irrI0NvTkYWK2ljMNyeLc9oxiPYEX7Kh6V9XAQOxwCNPh4EIXYaaMhCFlYbcsvSfZeaDQ7CX4sAHi6klm4GjQQ6Sx1r8jpyl9kQTkPcq3NIqP+yzkW7tj9kWCgi1faS4oPTEoYfzKpNZuWXdvT2o2b6dTxq6y/JDrUR6C94YjitYBAAxm8vVFH3yzYEh7b7x8O1h+rTTKJCsUfbXVBeIH90zZuEs5k6BHvCy7ezgp3ivStvWPH7LynujwlRPtlnRNYeHSXa6lkpzTOHH7fBYjIIFocjEwluyM/q6jWR/fooA0staapupEpBLoheasPpgoyXCIWy0XBcBvJmcM2UPf2nf/ZedywcVaeNc90OOZouFcT8h2hiX8Qamq+uVDBJZOkp6ontDu56RkS2rNOGIIKokMnnBez35PnF2QX1iMxyFtBprz4gjE8s1VqKhnisnzWstfrZC8iNghg+ATJvwNP2o=
  - secure: Xrdp5fr3584tljCKvfK80KKihYnozBBTwUFDtSfMJWyMe+pp/ye9aidmUkRAQqgbWTGcZeTWcn2wE7H1rNPCgH78hFMr0f54r9SM5dkvUu769a4Li3poDCEuovLTXeB9U+VdOKbVIV5N+ZBtZsah8qfxO8vp7OOG9rUCdOFFHl6eLkvIBVsiKEY1TpcTbfXHblvcqy0N2eU+S6NT/wC/tTviHYI8R8dinVy0pRQd6IETgfWFtwGqXZv6uQDNm5Tpk3Mr614qXgxNawRMzlTmIxsOkgG1mrzqSMVEnDNAGw7tfmeDeZDYK9ITM3yW41a/hQi2McMQq6xTe9TXrQE/lO+nHLra/PgKPVsQ2nmxrC356c2t2+CYEfVxAzmEIV3wdYcUYktBvKHdexcIEr9AmHPic1+Uteg62kIDdI18Lpg2NHW6EU+yykb+SAWUnlf5K5lzjRAKhbSQHpDC5r5NcN9lN782V9FirOtUzR8GhbClA988CWx7EWDyK3NoRPIVIuZMCSiQvwp97fcOo+xaBYH2oaEL3V5RgMO86gDIMNiJp2zfPOzMInQ1QFxbVUg2k35WvVIm0IWqya9vpq+PiXuLObDXB23j4QKEh3HvC2RTLWfFjwgNPLQ02PIwZG2xHIt37nllfoy/uArH4vWGxI36126Lcabm2R+4q+PHsVw=
notifications:
  slack:
    secure: FQycBnQsWuZ7KGinruTpQIe1FDlRfCBy8pXNSG15vBneukxo5OHaJongAvVVWwJVKcGD71TvgArSzUmKgJVVfOpWJ/ZnFzJgX8YaTmboybLR5JcncBo2qgbPpnNA4nIJXwLYcP2KwLeodKitYZp2fuAZgUGG1Hf3ToBhJJaADoLa1+wx05bs1ex1AOr64CeSIap0ElXYpq7ULvW3FXIaJJpAr6LsB4ocMaEO5GC3rdii5Ry82ZyC5nZid/M4p+znQUWqZMi7hY3PPAM18bfrz57okbhLeE5XTB2WKtjpW+M8Ir3FhJ+P0E6AkGj84MuN8PreYaVOUaD/lPRa0XJQ3Z9ct6GLkQWDT9yS5maPG9LgHjc1YbBDg+vLWKYn4j3J9rlI5xBpZulxHuIL/SiZo3BvR7MBSlbIHyJiaaV2w+UKlINvI6FUNuKDWlrot1FDLwpfmzb2RDaS7lTWG0lRqga9bfQljupDJES0p5eWZiHdP+kPIVjX8cVvgRBSzFM6kpNpkzZ0vi900SpBcw5kaLAbF3TwnjNBCEEm883g6VDZoWJ/VtlqpSy0WhEtKuKjsOmZnIn8NUXeo1EXQVGPw7L0xFloUwfX/A0mUMl2WwTzpq4iRGZ7bY00IyQ7m3o4v0L97IbgzprUercWqYkeEwSlbLo3srRvV0fbMCxgAx4=
