language: node_js
node_js:
  - "node"

jobs:
  include:
    - stage: yarn
      script: yarn
    - stage: linter
      script: yarn tslint
    - stage: unit tests
      script: yarn test
    - stage: build
      script: yarn prestart:prod