language: node_js
node_js:
  - "node"

stages:
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: build
      script: yarn tslint
      script: yarn test
      script: yarn prestart:prod
    - stage: deploy
      script: echo deploying