apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-07-22T20:13:48Z
  generation: 1
  labels:
    app: server
  name: msw-server-dev-dv
  namespace: default
  resourceVersion: "1164771"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/msw-server-dev-dv
  uid: be993391-8deb-11e8-8a13-56390b3e42ad
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: server
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: msw-server-dev
        image: myspecialway/msw-server:_62_env_support
        imagePullPolicy: Always
        name: msw-server-dv
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: 2018-07-22T20:13:48Z
    lastUpdateTime: 2018-07-22T20:16:13Z
    message: ReplicaSet "msw-server-dev-dv-655798457f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: 2018-07-22T20:47:37Z
    lastUpdateTime: 2018-07-22T20:47:37Z
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
