apiVersion: apps/v1
kind: Deployment
metadata:
  name: msw-server-dev-dv
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: msw-server-dv
          image: myspecialway/msw-server:latest
          ports:
          - containerPort: 3000
          envFrom:
            - configMapRef:
                name: msw-server-dev
      restartPolicy: Always
      