apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: msw-server-deployment
  labels:
    app: server    
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: server        
    spec:
      containers:
      - name: msw-server
        image: "myspecialway/msw-server:latest"
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: msw-server-dev
        ports:
        - name: http
          containerPort: 3000          
---
apiVersion: v1
kind: Service
metadata:
  name: msw-server-service
  labels:
    app: server    
spec:
  loadBalancerIP: 40.76.209.157
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: server